apiVersion: apps/v1
kind: Deployment

metadata:
  name: college-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: college-app

  template:
    metadata:
      labels:
        app: college-app

    spec:
      containers:
        - name: college-app

          image: riteshbansode/college-app:2.0

          imagePullPolicy: Always

          ports:
            - containerPort: 8090

          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: college-app-config
                  key: SPRING_DATA_MONGODB_URI
